---
  - name: create dir
    file:
      path: /opt/hub
      state: directory
    become: true

  - name: download archive
    get_url:
      url: "https://github.com/github/hub/releases/download/v{{ hub_version }}/hub-linux-amd64-{{ hub_version }}.tgz"
      dest: /opt/hub/hub.tgz

  - name: extract archive
    unarchive:
      src: /opt/hub/hub.tgz
      dest: /opt/hub

  - name: delete archive
    file:
      path: /opt/hub/hub.tgz
      state: absent

  - name: add to path
    file:
      src: "/opt/hub/hub-linux-amd64-{{ hub_version }}/bin/hub"
      dest: /usr/local/bin/hub
      owner: root
      group: root
      state: link
