---
  - name: "ensure package for CloudFoundry CLI is installed"
    apt:
      deb: "https://cli.run.pivotal.io/stable?release=debian64&version={{ cf_cli_version }}&source=github-rel"
      autoremove: yes